messages:
  no-homes: "§cYou have not set any homes."
  list-homes: "§cYou have the following homes: §6%h"

  set-home: "§cYou have set your §6%h§c home."
  del-home: "§cYou have deleted your §6%h§c home."

  invalid-home: "§cThat home §6%h§c does not exist."
  invalid-name: "§cThat is not a valid home name!"
  non-player: "Error: This command can only be run by a player."

players: